import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {cn} from '@/lib/utils';
import Link from 'next/link'
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { label: 'ホーム', href: '/'},
  { label: '二人対戦', href: '/match'},
  { label: 'AI対戦', href: '/vsAI'},
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={cn(inter.className, 'min-h-dvh')} style={{background: `#F2F2F2`,}}>
        <header className="container h-16 flex items-center border-b justify-between" style={{background: `#FFF`}}>
          <h1 className="font-bold">オセロウェブ</h1>
          <ul className="flex gap-4">
            {navItems.map((item => <li key={item.label}>
              
              <Button variant="ghost" asChild>
                <Link href={item.href}>{item.label}</Link>
              </Button>
            </li>))}
          </ul>
        </header>
      {children}

      <footer className="container sticky top-full h-16 flex items-center border-t">
        <p>&copy; yyyyhhhh</p>
      </footer>
      </body>
    </html>
  );
}
